name: finda
description: Finda is a shopping app, that allows you shop accross trusted vendors on instagram.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.3+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.0
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter:
    sdk: flutter
    
  flutter_feather_icons: ^2.0.0+1
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_it: ^6.1.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
  image_picker: ^0.8.4+3
  intl: ^0.17.0
  lint: ^1.5.3
  local_auth: ^1.1.8
  lottie: ^1.0.1
  package_info: ^2.0.0
  photo_view: ^0.13.0
  rive: ^0.7.3
  rive_loading: ^0.1.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  url_launcher: ^6.0.0-nullsafety
  wiredash: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "logo/finda.png"

# dev_dependencies:
#   flutter_test:
#     sdk: flutter


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/fonts/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 100
